apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-helloworld
  namespace: aks-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-helloworld
  template:
    metadata:
      labels:
        app: aks-helloworld
    spec:
      containers:
      - name: aks-helloworld
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"   
        env:
        - name: TITLE
          valueFrom:
            configMapKeyRef:
              name: custom-config
              key: title
---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld
  namespace: aks-test
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aks-helloworld
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aks-helloworld
  namespace: aks-test
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: 'true'
    kubernetes.io/ingress.class: addon-http-application-routing
    
spec:
  rules:
  - host: aks-helloworld.b853740bf1c7416a8df0.francecentral.aksapp.io
    http:
      paths:
      - backend:
          service:
            name: aks-helloworld
            port:
              number: 80
        path: /
        pathType: Prefix
