apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aks-helloworld-helm.fullname" . }}-config
  namespace: "{{ .Values.namespace }}"
  labels:
    {{- include "aks-helloworld-helm.labels" . | nindent 4 }}
data:
  {{- with .Values.configMapData }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
